apiVersion: v1
kind: Service
metadata:
    name: myapp
    namespace: app
    labels:
      app.kubernetes.io/name: myapp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: myapp
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080