apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mysql
  name: mysql
  namespace: hp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      containers:
      - image: 678092784151.dkr.ecr.us-east-1.amazonaws.com/myrepo:mysql
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        volumeMounts:
        - name: mysqldb
          mountPath: /var/lib/mysql
      volumes:
        - name: mysqldb
          hostPath:
            path: /tmp/sqldb
         
        
      