apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: assign3
  labels:
    app.kubernetes.io/name: mysql
    
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql